exp_name: 'pretrain'
seed: 20

train_jsons: [
  'data/json_files/BBC_Sound_Effects/bbc_final.json',
  'data/json_files/FreeSound/fsd_final.json',
  # 'data/json_files/SoundBible/sb_final.json',
  "data/json_files/AudioSet/train.json",
  "data/json_files/Clotho/train.json",
  "data/json_files/Clotho/train.json",
  "data/json_files/Clotho/train.json",
  "data/json_files/Clotho/train.json",
  #"data/json_files/AudioSet_SL/as_final.json",
  "data/json_files/Auto_ACD/train.json"
]
val_jsons: [
  "data/json_files/AudioSet/val.json",
  # "data/json_files/Clotho/val.json",
  # "data/json_files/Auto_ACD/val.json"
]
blacklist: "data/json_files/blacklist/blacklist_exclude_test_ac.json"
# dataset == 'AudioCaps': sampling_rate = 32000
# dataset == 'Clotho': sampling_rate = 44100
# 48000 for CLAP
# 32000 for HTSAT
audio_args:
  audio_length: 1024
  clip_samples: 480000
  mel_bins: 64
  sample_rate: 48000
  window_size: 1024
  hop_size: 480
  fmin: 50
  fmax: 14000
  class_num: 527
  model_type: "HTSAT"
  model_name": "base"

data_args:
  dataset: "Clotho"
  global_batch_size: 256
  batch_size: 16
  num_workers: 16

model_args:
  name: "CLAP2LLAMA"
  retr_prompt: ""
  task_prompt: ""
  caption_prompt : ""
  #retr_prompt: "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.\n\nUSER: Similar audio sounds and captions are given in pairs. "
  #retr_prompt: "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.\n\nUSER: "
  #task_prompt: "Describe this Audio in detail. "
  #task_prompt: "\nAnswer concisely. Briefly describe this Audio. Audio: "
  #task_prompt: "Briefly describe this Audio.\n Audio: "
  #task_prompt: "\nDescribe this Audio: "
  #caption_prompt : "\nASSISTANT: Caption: "
  freeze_am: True
  unfreeze_am: []
  # unfreeze_am: ["linear_a_q","linear_b_q","linear_a_v","linear_b_v"]
  freeze_lm: True
  freeze_align: False
  #checkpoint_path: "./pretrained_models/pretrained_MLP/" # 32, 16
  #checkpoint_path: "./pretrained_models/audio_caption_LGTM/"
  #checkpoint_path: "./pretrained_models/pretrained_LGTM/"
  #checkpoint_path: "./pretrained_models/pretrained_Qformer/"
  #checkpoint_path: "./pretrained_models/pretrained_Perceiver/"
  #checkpoint_path: "./pretrained_models/pretrained_MLP_15epoch_w16_s16/"
  #checkpoint_path: "./pretrained_models/pretrained_MLP_clap_lora/"
  #checkpoint_path: "./pretrained_models/pretrained_MLP_clap_lora_prompt/"
  #checkpoint_path: "./pretrained_models/pretrained_MLP_clap_lora_AutoACD/"
  #checkpoint_path: "./pretrained_models/encoder_whisper_LLAMA/"
  #checkpoint_path: "./pretrained_models/encoder_whisper_LLAMA/"
  checkpoint_path: ""
  encoder:
    model_name: "CLAPAudioEncoder"
    pretrained: True
    freeze: True
    spec_augment: True
    use_lora: True
    select_feature: "fine_grained_embedding"
    sequence_length: 1024
    hidden_size: 768
    window_size: 16 # (32,32) = [B,32,H], (32,16) = [B,63,H] (16,16) = [B,64,H], (8,8) = [B,128,H] (4,4) = [B,256,H]
    step_size: 16
  align:
    model_name: "MLP"


optim_args:
  lr: 1e-4
  betas: [0.9, 0.99]
  eps: 1e-8
  momentum: 0.9
  gamma: 0.1
  weight_decay: 0.0

training:
  warmup_epochs: 1
  epochs: 5
  clip_grad: 1
  output_path: "./pretrained_models/pretrained_MLP_aligned_with_LLAMA/"
  eval: False
  validate: False

index_args:
  index_path: ""
  # index_path: "./data/index/audiocaps_clotho_sentence_embed.json"
  #index_path: "./data/index/final_index_big_kb/audio2audio_train.json"
  #index_path: "./data/index/final_index_big_kb_pretrainQuery/audio2audio_pretrain.json"
  #index_path: "./data/index/final_index_big_kb/audio2audio_val.json"
  #index_path: "./data/index/final_index_big_kb/audio2text_val.json"
  #index_path: "./data/index/final_index_big_kb_clotho/audio2audio_val.json"
  #index_path: "./data/index/final_index_big_kb_clotho/audio2text_val.json"
  #index_path: "./data/index/final_index_big_kb/frame2frame_val.json"
  #index_path: "./data/index/final_index_big_kb/audio2text_val.json"
  #index_path: "./data/index/final_index_only_clotho/audio2audio_val.json"
  top_k: 0
