exp_name: 'pretrain'
device: "cuda"
seed: 20
json_files: [
  'data/json_files/BBC_Sound_Effects/bbc_final.json',
  'data/json_files/FreeSound/fsd_final.json',
  'data/json_files/SoundBible/sb_final.json',
  "data/json_files/AudioSet_SL/as_final.json",
  #"data/json_files/Clotho/clotho_final.json"
]
blacklist: "data/json_files/blacklist/blacklist_exclude_test_ac.json"
# dataset == 'AudioCaps': sampling_rate = 32000
# dataset == 'Clotho': sampling_rate = 44100
# 48000 for CLAP
# 32000 for HTSAT
audio_args:
  sr: 48000
  n_fft: 1024
  hop_length: 320
  f_min: 50
  f_max: 14000
  n_mels: 64
  max_length: 10
  mono: True

data_args:
  dataset: "Clotho"
  batch_size: 48
  num_workers: 8

model_args:
  name: "CLAP2GPT2"

optim_args:
  lr: 3e-5
  warmup_steps: 6400
  betas: [0.9, 0.999]
  eps: 1e-8
  momentum: 0.9
  gamma: 0.1
  warmup_epochs: 2
  step_epochs: 10
  weight_decay: 1e-6

training:
  epochs: 10
  clip_grad: 2
  dropout: 0.2